### ISSUE TITLE
login wont work

### ISSUE THREAD

**Issue by screwloose83** [flattery103/SimpleMSPDoc#5]
Hi.

I really like the idea of this. When i was setting up a test i found that the mysql tables are not created. (the install.php. Says they are tho.
I was able to manually create the mysql tables and then run the install and it added the user in so i could test it.

Thanks

**Comment by flattery103** [comment]
Thank you for catching this and putting in an issue. Sounds like it was missed in the install script, I will take a look and fix this.

**Comment by flattery103** [comment]
Unable to recreate. Did you run the install.php script?
Were the results of running the install script all successful?

Successful install should look like this:
<img width="384" alt="Screen Shot 2022-01-08 at 8 53 48 PM" src="https://user-images.githubusercontent.com/64496368/148667379-5bbc4ee4-1316-4762-83cd-a4def102596e.png">

**Comment by flattery103** [comment]
No issues found.
